name: EMSRwanda
description: Database Management Application for Laterite Ltd.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  barcode_scan:
  date_utils: "^0.0.1"
  flutter_sparkline: "^0.0.4"
  flutter_staggered_grid_view: "^0.1.4"
  intl: "^0.15.0"
  tuple: "^1.0.1"
  flutter_calendar: "^0.0.1"
  font_awesome_flutter: "^6.0.0"
  flutter_circular_chart:
  cloud_firestore:
  url_launcher:
  connectivity: "^0.3.1"
  firebase_storage: "^1.0.0"
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_analytics: ^0.3.3     # new
  firebase_auth:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true



  assets:
   - assets/data/regular_units.json
   - assets/icons/area.png
   - assets/icons/currency.png
   - assets/icons/digital_storage.png
   - assets/icons/length.png
   - assets/icons/mass.png
   - assets/icons/power.png
   - assets/icons/time.png
   - assets/icons/volume.png
   - assets/images/emma-watson.jpg
   - assets/images/microphone.png
   - assets/images/wallet.png
   - assets/images/joystick.png
   - assets/diamond.png
   - assets/ipad.jpg
   - assets/icons/availability.png



  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
   - family: Raleway
     fonts:
      - asset: third_party/Raleway-Regular.ttf
   - family: LineAwesome
     fonts:
      - asset: assets/fonts/line-awesome.ttf
   - family: Timeburner
     fonts:
      - asset: assets/fonts/timeburnernormal.ttf
      - asset: assets/fonts/timeburnerbold.ttf
        weight: 700

